import "jquery";
import "jquery-ui";
import "bootstrap/dist/css/bootstrap.min.css";
import "jquery-ui-dist/jquery-ui.css";
import "bootstrap";
import "bootbox";
import "./assets/css/font-awesome.css";
import "./assets/css/animations.css";
import "./assets/css/component.css";
import "./assets/css/base_style.css";
import "./assets/css/nav_menu.css";
import "./assets/css/sidebar_menu.css";
import "./assets/css/favor_menu.css";
import "./assets/css/program_style.css";
import "./assets/css/page_login.css";
import "./assets/css/page_first.css";
import "./assets/css/user_style_main.css";
import program_message from './assets/json/program_message.json';
import default_labels from './assets/json/default_label.json';
import program_labels from './assets/json/program_label.json';
import { initAppConfig } from "./assets/js/login.util";
import { appInit } from "@willsofts/will-app";
initAppConfig();
appInit({program_message,default_labels,program_labels,listen_messaging: 'parent'});
import { createApp, version } from 'vue';
import VueSure from './VueSure.vue';
console.log("Vue version",version);
createApp(VueSure).mount('#app');
